### ISSUE TITLE
v9 AppId/AppKey generation

### ISSUE THREAD

**Issue by PhyxionNL** [Jumoo/uSync.Complete.Issues#134]
**Describe the bug**
Generating an appid/appkey doesn't seem to work correctly at the moment. If I open dev tools I can see json getting returned with a bunch of keys, but this is not shown anywhere to the user, and uSync doesn't seem to use the generated keys either (at least it's not shown in the UI).

**Version (please complete the following information):**
 - Umbraco Version: 9 rc 2
 - uSync Version 9 rc 2
 - uSync.Complete Version 9 beta 5

**Comment by KevinJump** [comment]
HI, sorry for this -  but for later builds this functionality is/has been changed quite a bit in later builds.  

For the public beta it was still in there, but we have since taken the decision that we are not going to change appsettings from the UI (the new release will show you what to put where in the file, but it will not setup the server in the same way as v8 does

we do have later nightly builds on our public nightly server - but these are not super stable at the moment, but if you want to check things. :

https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json

**Comment by PhyxionNL** [comment]
No problem @KevinJump, I thought I'd just report a few issues I've came across. I already expected some would be fixed. I think that's a better solution. I had already added that NuGet feed but it doesn't seem to serve nightly builds of the complete edition (only normal uSync + dependencies).

**Comment by PhyxionNL** [comment]
@KevinJump Have you checked the NuGet feed? It's still not showing nightly builds here for Complete (and most others).

**Comment by KevinJump** [comment]
HI, yeah sorry the code wasn't in an ideal state there for a few days while we took the chance to reactor a few things. 

the nightlies are back now - currently version `9.0.0-beta005.20210917.3`  - works reasonably well - we are just tiding up a few loose ends before a likely RC next week .

**Comment by PhyxionNL** [comment]
Thanks. I just tried my first sync and there are some problems.

1. In root content node ("Content"), select server (pull), and nothing happens. This is logged in developer console:

> Possibly unhandled rejection: {"data":{"ExceptionMessage":"Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'Umbraco.Cms.Core.Udi' because the type requires a JSON string value to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON string value or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'folders[0].udi.uriValue', line 1, position 131.","ExceptionType":"Newtonsoft.Json.JsonSerializationException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","StackTrace":"   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at uSync.Publisher.Publishers.SyncBrowsingPublisher.GetContentFolders(Guid id, String target)\r\n   at uSync.Publisher.Controllers.uSyncPublishApiController.GetContentFolders(Guid id, String server)\r\n   at lambda_method3476(Closure , Object )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/umbraco/backoffice/usync/usyncpublishapi/GetContentFolders?id=00000000-0000-0000-0000-000000000000&server=test","headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","X-UMB-SEGMENT":null}},"statusText":"Internal Server Error","xhrStatus":"complete"}

2. Push also fails:
TypeError: uSyncPublishDialogManager.openPublisherDialog is not a function

3. Some documents fail on Calculating .... with everything checked. For example, when I select some document > Do something else > Publish to... > select server > Calculating "document". It works with this config (both need to be unchecked): 
![image](https://user-images.githubusercontent.com/7643972/133808565-2b75595a-6228-449b-a78f-2de9cf4ffbcb.png)
I don't see anything logged in console despite having "ReportDebug" on true. 

4. Snapshots don't seem to do anything.

**Comment by KevinJump** [comment]
Hi, 

:(  - that all works for me on a clean install. Maybe i am forgetting something in the setup that needs to be documented. 

you might need to increment the caching value in umbraco (to get the js/files etc reloaded). 

also can you confirm what versions of everyhing (umbraco included) you are running, 

and this will probibly/certainly not work on linux just at the moment .

**Comment by KevinJump** [comment]
yeah sorry - pull is broken. in that build. fixing now.

**Comment by PhyxionNL** [comment]
Here:

Umbraco.Cms" Version="9.0.0-rc003"
uSync.Complete" Version="9.0.0-beta005.20210917.4"

Cache I already cleared. I'm not running it on Linux. I've gotten logging to work and it's hanging on this:
[17:59:39 DBG] Checking for DocType Dependencies, Umbraco.ColorPicker.EyeDropper

**Comment by PhyxionNL** [comment]
Alright, I've saved the document type that used the eye dropper again and now it does get on with it. That said, calculating is super slow and waits a long time at the eye dropper (only one document uses it). MultiUrlPicker is also very slow. I tried to push from my root node ("Home") and it takes at least 15 minutes to calculate. There is not a whole lot of content (~120 documents) on the site. I will give the cache a try and see if it speeds things up.

Some other things (you might've seen it already):
1. Before "Publish to server", there's null before the URL:
![image](https://user-images.githubusercontent.com/7643972/133820933-b4d44c8c-ae20-4fae-a458-1d2d07ecc8fc.png)

2. Missing snapshot icons:
![image](https://user-images.githubusercontent.com/7643972/133821094-81efee38-2909-480c-ae27-c27cc78852a1.png)

3. Snapshots I really can't get working. Nothing is logged in app and browser console either.
![image](https://user-images.githubusercontent.com/7643972/133821518-7e65b8af-9da7-48c5-a870-9e190643acbb.png)

**Comment by PhyxionNL** [comment]
Got one to send, but it didn't succeed.
This is thrown on receiving side:

> System.IO.DirectoryNotFoundException: pack folder : umbraco\Data\TEMP\uSync\receive\ad5343ae-74bd-4703-85b3-4b3f5de8e052\uSync does not exsit when it should
> at uSync.Expansions.Core.Physical.SyncPackFileService.EnsurePackFolder(System.String folder) at offset 56
> at uSync.Expansions.Core.Services.SyncPackService.ImportItems(uSync.Expansions.Core.SyncPackRequest request)
> at uSync.Publisher.Services.SyncPublishService.ImportItems(uSync.Publisher.Models.SyncPublishRequest request) at offset 14
> at uSync.Publisher.Controllers.uSyncReceiveApiController.DoPublisherStep(uSync.Publisher.Models.PublisherActionRequest options, System.Func`2 action) at offset 127
> at uSync.Publisher.Controllers.uSyncReceiveApiController.ImportPackFolder(uSync.Publisher.Models.PublisherActionRequest options) at offset 19

On sender:
`Remote Error: Redirect (/) Content: []`
Which I suspect is happening as I handle unhandled exceptions by redirecting to the home page.

**Comment by KevinJump** [comment]
:( - the pull is going to be something i look at next week, after tracking it down, turns out i had put one of the zip to stream in .netcore methods into a to hard to do just now pile, and not then gone back (doh!).

other stuff, are you running on a published site (e.g dotnet publish) or a dev site. its not that slow for me, and pushing works, as does all the snapshot stuff, there is a chance i've messed things up. 

_you should double check that all the caching of files has been resolved by smidge. i think the cache buster for smidge defaults to version or something, so if you change it to AppDomain it will change on restart (so no cached js files)._

in appsettings.json its something like (obviously with more config in umbraco than just this)
```
"Umbraco": {
      "RuntimeMinification": {
        "cacheBuster": "AppDomain"
      }
}
```

**Comment by PhyxionNL** [comment]
> :( - the pull is going to be something i look at next week, after tracking it down, turns out i had put one of the zip to stream in .netcore methods into a to hard to do just now pile, and not then gone back (doh!).
> 

No problem, I'll give that a try then.

> other stuff, are you running on a published site (e.g dotnet publish) or a dev site. its not that slow for me, and pushing works, as does all the snapshot stuff, there is a chance i've messed things up.
> 

Both, the receiving end is published, the sender is just running the build locally (without debugger). Without logging it's a bit faster but not much. Maybe 2 minutes faster.

> _you should double check that all the caching of files has been resolved by smidge. i think the cache buster for smidge defaults to version or something, so if you change it to AppDomain it will change on restart (so no cached js files)._
> 
> in appsettings.json its something like (obviously with more config in umbraco than just this)
> 
> ```
> "Umbraco": {
>       "RuntimeMinification": {
>         "cacheBuster": "AppDomain"
>       }
> }
> ```

I had already removed all cached files from Smidge to try. I use a custom cache buster for Smidge based on last modified file, but even when Smidge is disabled it's not working.

**Comment by KevinJump** [comment]
HI, 
- we've fixed pull!,
- and added some logging for the dependency stuff ! - so if you have uSync logging turned to debug (Add `"uSync":  "Debug"` to the overrides seection of the serilog config in appsettings.json). you should see some timings for the dependency check which will hopefully help pinpoint any issues

also in an effort to help you see whats going on, I am going to try and log the changes we are making for nightlies : https://github.com/Jumoo/uSync.Complete.Issues/blob/main/log/nighly.md

**Comment by PhyxionNL** [comment]
Thanks @KevinJump. A changelog is useful. 

I have installed 9.0.0-beta005.20210918.8. If I press Remote (Pull) at the root dashboard the Umbraco.Cms.Core.Udi exception is still printed in browser console and nothing happens after it. Local (Push) is also broken, the "Push selection" button isn't doing anything. 
Publishing and pulling through "More actions" does work if I start it from the same content item.
The Sync page from Publisher page fails here with "Error while processing SettingsPull - (pullFetch/Calculate/0/)":
![image](https://user-images.githubusercontent.com/7643972/133986690-1322a261-d7ac-43ed-a26e-5b5368356307.png)

Snapshot creation ignores the root folder I have set in app settings. Apply and Report of a snapshot does not show any progress:
![image](https://user-images.githubusercontent.com/7643972/133984019-ce7c1958-5a9b-4ad3-863e-c02d94f153b8.png)
In app console I do see progress being made (with Debug to Serilog). After this all is done there is a final changes report shown on the browser dashboard. Snapshots settings saving does not work, but going by your previous replies, I suspect this will be removed.

**Comment by KevinJump** [comment]
Hi,

Snapshot and Browser (Remote(pull)/Local(Push) dashboard are fixed in the new build (`9.0.0-beta005.20210920.2`)

I am not sure the remote error was a UDI errors - but if they are still happening after this update - they are coming for the serialization phase (i think the problem is when its turned into JSON its not going via the umbraco UDI converter) - do you have any customization of serialization anywhere ?

**Comment by PhyxionNL** [comment]
Updated and the main dashboard is indeed working now (both push and pull), nice work 👍

I have also disabled redirects from /umbraco pages to get you the correct URL from the error on the Sync page:
```Error while processing SettingsPull - (pullFetch/Calculate/0/) - Remote Error: InternalServerError (/umbraco/uSyncReceive/uSyncReceiveApi/PullGetItems) Content: [] ```

**Comment by KevinJump** [comment]
Hi, is there anything on the logs of the server you are pulling from around that error ?

**Comment by PhyxionNL** [comment]
I didn't have logging enabled there, but I've run it again, here:

```
2021-09-20 14:11:32.548 +02:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at uSync.Expansions.Core.ItemManagers.Managers.SyncLanguageItemManager.<>c__DisplayClass2_0.<GetDecendants>b__0(ILanguage x)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at uSync.Core.Sync.SyncItemManagerBase.GetItems(SyncItem item)
   at uSync.Expansions.Core.Services.SyncItemService.GetItems(SyncItem item)
   at uSync.Expansions.Core.Services.SyncItemService.GetAllItems(IEnumerable`1 items)
   at uSync.Publisher.Services.SyncPublishService.GetAllItems(Guid id, IEnumerable`1 items)
   at uSync.Publisher.Controllers.uSyncReceiveApiController.PullGetItems(PublisherActionRequest request)
   at lambda_method58(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Website.Middleware.PublicAccessMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
```

**Comment by KevinJump** [comment]
Its a little strange because the `SyncLanguageItemManager ` doesn't have a method with that signature 🤔 it might be coming from the internal umbraco methods . but i am not sure. 

I've put some extra checks around languages in the latest build `beta005.20210920.4`  - might fix it, might also log some more info to tell us what is wrong

**Comment by PhyxionNL** [comment]
Same exception:

```
2021-09-20 15:39:23.570 +02:00 [DBG] Calling Item Manager: uSync.Expansions.Core.ItemManagers.Managers.SyncLanguageItemManager
2021-09-20 15:39:23.570 +02:00 [DBG] GetDecendants: Languages umb://language/00000000-0000-0000-0000-000000000000
2021-09-20 15:39:23.571 +02:00 [DBG] Getting single language: 00000000-0000-0000-0000-000000000000
2021-09-20 15:39:23.580 +02:00 [DBG] Get Sync items completed [10ms]
2021-09-20 15:39:23.585 +02:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at uSync.Expansions.Core.ItemManagers.Managers.SyncLanguageItemManager.<>c__DisplayClass3_0.<GetDecendants>b__0(ILanguage x)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at uSync.Core.Sync.SyncItemManagerBase.GetItems(SyncItem item)
   at uSync.Expansions.Core.Services.SyncItemService.GetItems(SyncItem item)
   at uSync.Expansions.Core.Services.SyncItemService.GetAllItems(IEnumerable`1 items)
   at uSync.Publisher.Services.SyncPublishService.GetAllItems(Guid id, IEnumerable`1 items)
   at uSync.Publisher.Controllers.uSyncReceiveApiController.PullGetItems(PublisherActionRequest request)
   at lambda_method54(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Website.Middleware.PublicAccessMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 119
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
```

**Comment by KevinJump** [comment]
Ahh found it. on the sync dashboard, we where setting language UDI like a guid based on, when its actually a string based UDI. 

fixed in `beta005.20210920.5`

**Comment by PhyxionNL** [comment]
It works now 🎉. With this I've also noticed that the recycle bin isn't properly synchronized. I removed some content locally from recycle bin and pushed the changes to remote, but the Sync page is now trying to pull the items back from the recycle bin from remote.

The rest all seems to work now (apart from the previously mentioned snapshot settings and initial progress for snapshot report/apply.
