### ISSUE TITLE
Error when trying to push content to remote server

### ISSUE THREAD

**Issue by karltynan** [Jumoo/uSync.Complete.Issues#247]
**Describe the bug**
When trying to push to a remote server, I get the following error:
```
Value cannot be null. (Parameter 'configuration')
    at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.GetValue[T](IConfiguration configuration, String key, T defaultValue)
   at uSync.Forms.Dependencies.FormPickerChecker.GetDependencies(IContent item, DependencyFlags flags)
   at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.GetDependencies(TObject item, DependencyFlags flags)
   at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.GetDependencies(Guid key, DependencyFlags flags)
   at uSync.Expansions.Core.Cache.SyncCacheService.GetInternalDependency(ISyncHandler handler, Udi udi, DependencyFlags flags, SyncCacheOptions options)
   at uSync.Expansions.Core.Cache.SyncCacheService.GetDependencies(ISyncHandler handler, Udi udi, DependencyFlags flags, SyncCacheOptions options)
   at uSync.Expansions.Core.Services.SyncDependencyService.GetHandlerDependencies(ISyncHandler handler, String handlerSet, Udi udi, DependencyFlags flags, Boolean allowRootClean)
   at uSync.Expansions.Core.Services.SyncDependencyService.GetItemDependency(SyncItem item, String handlerSet, IList`1 existing, Boolean allowRootClean)
   at uSync.Expansions.Core.Services.SyncDependencyService.GetDependencies(SyncPackRequest request)
   at uSync.Publisher.Services.SyncPublishService.GetDependencies(SyncPublishRequest request)
   at uSync.Publisher.Publishers.SyncRealtimePublisher.PushCalculate(PublisherActionRequest request)
   at uSync.Publisher.Services.SyncPublisherActionService.PerformAction(PublisherActionRequest request, ISyncPublisher publisher, IUser user)
```
I have a new root node (+ children) on staging I'd like to promote to production. No other nodes on staging are on production, I am just moving this one for now.

Not sure if it is something to do with the FormPicker or not? I do recall at some point in the past seeing an error/warning in uSync area about the form picker did not have a valid mapper (or similar).

The only other thing that might be worth noting, but doesn't feel applicable, is we have enabled [external login providers](https://docs.umbraco.com/umbraco-cms/13.latest-lts/reference/security/external-login-providers).

We have seen this working before, so not sure if this is something new.

**Version (please complete the following information):**
 - **Umbraco Version:** 13.5.2
 - **uSync Version:** v13.2.5 + Exporter (v13.1.7), Snapshots (v13.1.7), PeopleEdition (v13.1.7), Publisher (v13.1.7), Complete (v13.1.7), FormsEdition (v13.4.0.0)

**Screenshots**
![image](https://github.com/user-attachments/assets/217f6611-db00-4108-8bb4-b5e9acc913d3)

**Comment by KevinJump** [comment]
Hi, 

We had an issue (with the config property on non-windows builds), but it was fixed in uSync.Forms v13.4.1 so if you upgrade to that it should be OK ?

**Comment by karltynan** [comment]
That did the trick! Thanks.

**Comment by karltynan** [comment]
We did see an issue after pushing actually, where any form with the same name seemed to have merged with each other. The structure was:

- **Forms**
  - **Folder A**
    - _A Form Name (not affected)_
    - Duplicate Form Name*
    - A N Other Duplicate Form Name*
  - **Folder B**
    - _B Form Name (not affected)_
    - Duplicate Form Name*
    - A N Other Duplicate Form Name*

Forms with duplicate names in Folder B moved some of their fields/workflows into the form with the same name in Folder A, and vice versa in some cases. Unique named forms were unaffected.

Does the form sync/comparison need to have a unique name?

**Comment by bielu** [comment]
@karltynan I think i fixed this issue when working on https://github.com/KevinJump/uSync.Forms/issues/22 if you can check and let me know. 
the forms version is 13.4.4
