### ISSUE TITLE
Exporting fails - when site is using grid style attributes with pre-values. 

### ISSUE THREAD

**Issue by loriRyanp** [Jumoo/uSync.Complete.Issues#71]
After upgrading I am having a lot of problems exporting content. I keep getting the following 
Any help in how to resolve would be most welcome.
Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'sections[0].rows[1].styles.background-color'.
   at Newtonsoft.Json.JsonReader.ReadAsString() in /_/Src/Newtonsoft.Json/JsonReader.cs:line 500
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter) in /_/Src/Newtonsoft.Json/JsonReader.cs:line 1219
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1435
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 545
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 196
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2070

**Comment by KevinJump** [comment]
Hi, I'll take a look at that, 

Can you confirm the version of uSync/ContentEdition and uSync.Complete you have installed.  ?
and is this an export from the uSync dashboard. or the exporter or during a publish.

**Comment by loriRyanp** [comment]
Hi Kevin
Its happening on both when I go to publish a page via the tree node or from the  exporter.
uSync.Complete 8.8.0
Usync 8.7.2

**Comment by KevinJump** [comment]
Hi, 

can you share your grid style settings - i suspect its in there just want to make sure i have the same setup.

**Comment by KevinJump** [comment]
also if you can locate the .config file in the usync\v8 folder for the problem content that would be a great help (feel free to email me that file if you don't want to share it kevin@jumoo.co.uk)

**Comment by loriRyanp** [comment]
Thats sent also just got the following No Step alias? - Increment your ClientDependency version? Parameter name: StepAlias

**Comment by KevinJump** [comment]
I suspect that error is related.

**Comment by KevinJump** [comment]
Hi, we have a fix for this. its actually in the uSync element, we can ship a quick fix for this (it will be an update of uSync.ContentEdition) - are you using nuget for your site, or will you need a package/dll ?

**Comment by loriRyanp** [comment]
Nuget please thank you so much for the quick turn around.

**Comment by KevinJump** [comment]
Hi, 
publishing the patch version now : 

Release for content edition is: 8.7.2.1 
https://www.nuget.org/packages/uSync.ContentEdition/8.7.2.1

```
update-package uSync.ContentEdition -version 8.7.2.1 -FileConflictAction Ignore
```

**Comment by loriRyanp** [comment]
Hi Kevin
Sorry just tried
Unable to resolve dependencies. 'uSync 8.7.2' is not compatible with 'uSync.ContentEdition
8.7.2.1 constraint: uSync (>= 8.7.2.1)

**Comment by loriRyanp** [comment]
No worries – thanks again
Any place I pop some dough to get you a coffee?
