### ISSUE TITLE
Unrecognized escape sequence \T.

### ISSUE THREAD

**Issue by Nuklon** [Jumoo/uSync.Complete.Issues#93]
**Describe the bug**
```csharp
parsing "bin\Test" - Unrecognized escape sequence \T.
   at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
   at System.Text.RegularExpressions.RegexParser.ScanBasicBackslash()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern, RegexOptions options)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at uSync.Expansions.Core.Services.SyncPackService.LoadRequiredFiles(SyncPackRequest request, String hashFile)
   at uSync.Expansions.Core.Services.SyncPackService.ImportFiles(SyncPackRequest request, String hashFile)
   at uSync.Publisher.Services.SyncPublishService.ImportWebsiteFiles(SyncPublishRequest request)
   at uSync.Publisher.Publishers.SyncRealtimePublisher.<PullImportFiles>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at uSync.Publisher.Controllers.uSyncPublisherApiController.<PerformAction>d__10.MoveNext()
````
**To Reproduce**
Import content from a remote site.

**Additional context**
uSync 8.9.1.

**Comment by KevinJump** [comment]
Hi, 

just to clarify is this via a 'sync-pack' using the exporter ?

**Comment by Nuklon** [comment]
I'm not that familiar with the names. What I did: select a node in Umbraco > ... > Do something else > Pull content... (push from other side has the same error) > keep everything selected. Then it loads for a bit (not that long) and this error comes up. If I uncheck most of the stuff below Advanced options it's going through.

**Comment by KevinJump** [comment]
Hi, i think you have an old/corrupt setting in your uSync.Publish.config file.

the system exclusions setting stops uSync coping over itself between sites. (and can be configured to not copy other things).
```
<systemExclusions>bin\\uSync,app_plugins\\uSync,bin\\App_Data</systemExclusions>
```

these are regex expressions so need the double slash. - i think you might have something in there that isn't a valid expression. 

Kevin

**Comment by KevinJump** [comment]
Hi, just to update we might have an issue - checking it now, 

we add and exclusion based on project name (based on any *.csproj file in the site root). its possible for us to then get an invalid regex expression loaded. so we might have to clean it up.

**Comment by Nuklon** [comment]
OK, thanks. I checked `systemExclusions` on both ends and it seems correct:

```xml
  <systemExclusions>bin\\uSync,app_plugins\\uSync</systemExclusions>
```
My csproj doesn't contain spaces (not sure if that's related though).

**Comment by KevinJump** [comment]
think i've fixed it but out of interest what is your csproj file name ?

**Comment by Nuklon** [comment]
It's TestUmbraco8.

**Comment by rly-nozebra** [comment]
I've got the exact same issue, except the file parsing is bin\MyProjectName

**Comment by KevinJump** [comment]
yeah - i think it's fixed - we just need to sanitize & text the next release to push it out.

**Comment by rly-nozebra** [comment]
It seems like it's the automated insert of the project dll in the exclude which misses a \

**Comment by KevinJump** [comment]
yeah it is. but also we've added a little bit of extra code to clean up any stuff that might get added via config and is incorrect.

**Comment by rly-nozebra** [comment]
@KevinJump Do you have any idea on, when 8.9.3 is released?

**Comment by KevinJump** [comment]
Hi - it should be today. 

We where just halted as we where holding as someone said they had an issue, but i think it turns out they didn't so we should be able to do the checking and release stuff now.

**Comment by rly-nozebra** [comment]
Cool. Sounds great :-)

**Comment by KevinJump** [comment]
HI 8.9.3 is released now.
